---
title: "16_20"
author: "jialei"
date: "2021/9/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(tidyverse)
library(ggthemes)
library(ggspatial)
library(units)
library(nngeo)
```

```{r}
weibo <- st_read("C:/Users/Jialei/Documents/spatial analysis/spatial_3/weibo/weibo.shp")

school <- st_read("C:/Users/Jialei/Documents/spatial analysis/spatial_3/school/school.shp")

greenspace <- st_read("C:/Users/Jialei/Documents/spatial analysis/spatial_3/greenspace/greenspace.shp")

township <- st_read("C:/Users/Jialei/Documents/spatial analysis/spatial_3/township/township.shp")
```


```{r}
pseudo_mercator <- "+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"

weibo <- weibo %>%
  st_transform(pseudo_mercator)

school <- school %>%
  st_transform(pseudo_mercator)

greenspace <- greenspace %>%
  st_transform(pseudo_mercator)

township <- township %>%
  st_transform(pseudo_mercator)
```

```{r}
ggplot(township)+
  annotation_map_tile(zoomin = 0, progress = "none") +
  labs(caption = "Map tiles and data by OpenStreetMap")+
  geom_sf(fill = "grey", color = "white")+
  geom_sf(data = weibo, color = "red", size = 0.01)+
  theme_map()
 
```

```{r}


township <- township %>%
  mutate(num_weibo = lengths(st_covers(township, weibo)))

mean(num_weibo)

left_side  <- st_bbox(weibo)$xmin
top_side <- st_bbox(weibo)$ymax

ggplot(township) +
  geom_sf(color = NA, 
          aes(fill = num_weibo)) +
  scale_fill_viridis_c(name = "Jiaxing townships\nby number of Weibo posts",
                       breaks = breaks <- seq(0, 10000, by = 500),
                       labels = paste(prettyNum(breaks, big.mark = ","),
                                      "Weibo posts")) +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr",
                         style = north_arrow_minimal()) +
  annotate(geom = "text", x = left_side, 
           y = top_side, 
           label = paste("Average number:", 
                         prettyNum(mean(num_weibo), big.mark = ","),
                         "Weibo posts in Jiaxing\n", 
                         sep = ""),
           hjust = 0, vjust = 0, size = 3) +

theme_map() +
  theme(legend.background = element_rect(fill = alpha("white", 0.5), 
                                         color = "gray"))

```

```{r}

township <- township %>%
  mutate(area = set_units(st_area(township), km^2)) %>%
  mutate(weibo_dens = as.numeric(num_weibo / area))

ggplot(township[which(township$weibo_dens > 0.5),]) +
  geom_sf(color = NA, 
          aes(fill = weibo_dens)) +
    scale_fill_viridis_c(name = 
                           "Jiaxing Townships\nby weibo posts density",
                         breaks = breaks <- c(0.01, 0.1, 1, 10, 100, 1000), trans = "log",
                       labels = paste(prettyNum(breaks, big.mark = ","),
                                      "posts per square km")) +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr",
                         style = north_arrow_minimal()) +
theme_map() +
  theme(legend.position = "right",
    legend.background = element_rect(fill = alpha("white", 0.5), 
                                         color = "gray"))

```

```{r}
greenspace <- greenspace %>%
  mutate(num_weibo = lengths(st_covers(greenspace, weibo)))
  
ggplot(greenspace) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "osmgrayscale") +
  geom_sf() +
  labs(caption = "Map tiles and data by OpenStreetMap")+
  geom_sf(color = NA, 
          aes(fill = num_weibo)) +
    scale_fill_viridis_c(name = 
                           "Jiaxing Greenspaces\nby number of weibo posts",
                       breaks = breaks <- c(0.01, 0.1, 1, 10, 100, 1000), trans = "log",
                       labels = paste(prettyNum(breaks, big.mark = ","),
                                      "weibo posts")) +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr",
                         style = north_arrow_minimal()) +
  theme_map() +
  theme(legend.position = "right",
    legend.background = element_rect(fill = alpha("white", 0.5), 
                                         color = "gray"))
```



```{r}
greenspace <- greenspace %>%
  mutate(num_weibo = lengths(st_covers(greenspace, weibo)))

greenspace <- greenspace %>%
  mutate(area = set_units(st_area(greenspace), km^2)) %>%
  mutate(weibo_dens = as.numeric(num_weibo / area))

ggplot(greenspace) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "osmgrayscale") +
  geom_sf() +
  labs(caption = "Map tiles and data by OpenStreetMap")+
  geom_sf(color = NA, 
          aes(fill = weibo_dens)) +
    scale_fill_viridis_c(name = 
                           "Jiaxing Greenspaces\nby number of weibo posts",
                       breaks = breaks <- c(0.01, 0.1, 1, 10, 100, 1000), trans = "log",
                       labels = paste(prettyNum(breaks, big.mark = ","),
                                      "posts per square km")) +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr",
                         style = north_arrow_minimal()) +
theme_map() +
  theme(legend.position = "right",
    legend.background = element_rect(fill = alpha("white", 0.5), 
                                         color = "gray"))
```
```{r}
